StartupEvents.registry("item", event => {
    event.create("createsifter:tin_mesh", "createsifter:mesh")
        .displayName({ translate: "item.createsifter.tin_mesh" })
        .parentModel("createsifter:block/meshes/mesh")
        .texture("mesh", "tlhisland:item/tin_mesh")
        .maxDamage(12)

    event.create("createsifter:copper_mesh", "createsifter:mesh")
        .displayName({ translate: "item.createsifter.copper_mesh" })
        .parentModel("createsifter:block/meshes/mesh")
        .texture("mesh", "tlhisland:item/copper_mesh")
        .maxDamage(24)

    event.create("createsifter:osmium_mesh", "createsifter:mesh")
        .displayName({ translate: "item.createsifter.osmium_mesh" })
        .parentModel("createsifter:block/meshes/mesh")
        .texture("mesh", "tlhisland:item/osmium_mesh")
        .maxDamage(128)

    event.create("tlhisland:sale_license")
        .displayName({ translate: "item.tlhisland.sale_license" })
        .parentModel("minecraft:item/generated")
        .texture("tlhisland:item/sale_license")
        .maxStackSize(1)
    
    event.create("tlhisland:purchase_license")
        .displayName({ translate: "item.tlhisland.purchanse_license" })
        .parentModel("minecraft:item/generated")
        .texture("tlhisland:item/purchase_license")
        .maxStackSize(1)

    event.create("tlhisland:mehvahdjukaars_foolish")
        .displayName({ translate: "item.tlhisland.mehvahdjukaars_foolish"})
        .parentModel("minecraft:item/generated")
        .texture("minecraft:item/copper_ingot")
        .tooltip(Component.translatable("item.tlhisland.mehvahdjukaars_foolish.tooltip").color(Color.GRAY).italic())
        .tooltip(Component.translatable("item.tlhisland.mehvahdjukaars_foolish.tooltip1").color(Color.GRAY).italic())
        .tooltip(Component.translatable("item.tlhisland.mehvahdjukaars_foolish.tooltip2").color(Color.GRAY).italic())
        .tooltip(Component.translatable("item.tlhisland.mehvahdjukaars_foolish.tooltip3").color(Color.GRAY).italic())
        .tooltip(Component.translatable("item.tlhisland.mehvahdjukaars_foolish.tooltip4").color(Color.GRAY).italic())
        .maxStackSize(1)
})